### ISSUE TITLE
Invalid type for comparison error

### ISSUE THREAD

**Issue by Tohrusenpai** [FravBox/YagCCs#3]
Hi Vars,

Thank you for sharing this fantastic reaction ticket post code!  I've seen it at work in other servers and I love it.  Hoping to get it working in mine  now. =)

I set up the code provided on YAGPDB's web portal and ran it in my discord but ran into an error related the to reaction.  I've tried figuring out the cause on my own but I'm not having much luck.  Wondering if you are aware of this and have a solution?  Couldn't find you in the YAG Discord (as your profile suggests) to message you directly there, sorry.  You are welcome to send me a friend request on Discord (Lilyana#9762) if you'd like to talk through the issue at length or have questions. 

Here are some screenshots of the issue.
![image](https://user-images.githubusercontent.com/117125036/199120117-62ffad38-418e-4054-ac00-3b1ffb3e1454.png)
![image](https://user-images.githubusercontent.com/117125036/199120284-33849365-1a65-4319-b811-28915a6f472f.png)
![image](https://user-images.githubusercontent.com/117125036/199120376-2e17ebf2-fee7-463f-9791-ebfe9e7b01cd.png)

**Comment by Tohrusenpai** [comment]
Nevermind, someone helped me figure out that it's because I had the trigger type set to "command" instead of "reaction" - whoops!  No issue needs fixing, though maybe a comment at the top or bottom of the code would help others avoid the same issue =)

**Comment by FravBox** [comment]
Sorry, I was out of town for this - but it looks like I do have a note at the top lol
